# This file is part of deployment-tool.
# Copyright (C) 2014-2016  Sequent Tech Inc <legal@sequentech.io>

# deployment-tool is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License.

# deployment-tool  is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with deployment-tool.  If not, see <http://www.gnu.org/licenses/>.

---
- name: sequent-ui, copy logo image
  when: config.sequent_ui.organization.logo_path != ''
  become: true
  copy:
    src: "{{config.sequent_ui.organization.logo_path}}"
    dest: /home/ui_user/admin-console/img/Sequent_logo_small.png
    owner: ui_user
    group: ui_user
    mode: u=rw,g=r,o=r

- name: sequent-ui, config beautify options
  become: true
  become_user: ui_user
  replace:
    dest: "/home/ui_user/{{item}}/Gruntfile.js"
    regexp: 'beautify:.*'
    replace: "beautify: {% if config.sequent_ui.debug == 'true' %}true{% else %}false{% endif %}"
  with_items:
    - admin-console
    - election-portal
    - voting-booth

- name: sequent-ui, config compress options
  become: true
  become_user: ui_user
  replace:
    dest: "/home/ui_user/{{item}}/Gruntfile.js"
    regexp: 'compress:.*'
    replace: "compress: {% if config.sequent_ui.debug == 'false' %}{}{% else %}false{% endif %},"
  with_items:
    - admin-console
    - election-portal
    - voting-booth

- name: sequent-ui, copy static_extra_path
  when: config.sequent_ui.static_extra_path != ''
  become: true
  copy:
    src: "{{config.sequent_ui.static_extra_path}}"
    dest: /home/ui_user/static_extra/
    owner: ui_user
    group: ui_user

- name: sequent-ui, config election limits
  become: true
  become_user: ui_user
  replace:
    dest: /home/ui_user/admin-console/avAdmin/election-limits-service.js
    regexp: '{{ item.key }}:.*'
    replace: '{{ item.key }}: {{ item.value }},'
  with_items:
    - key: maxNumQuestions
      value: "{{ config.election_limits.max_num_questions }}"

    - key: maxNumAnswers
      value: "{{ config.election_limits.max_num_answers }}"

    - key: maxShortStringLength
      value: "{{ config.election_limits.max_short_string_length }}"

    - key: maxLongStringLength
      value: "{{ config.election_limits.max_long_string_length }}"

- name: sequent-ui, config custom html body include
  become: true
  become_user: ui_user
  replace:
    dest: /home/ui_user/admin-console/Gruntfile.js
    regexp: 'admin_html_body_include:.*'
    replace: 'admin_html_body_include:"{{ config.sequent_ui.texts.admin_html_body_include | regex_replace("\n", "") }}",'

- name: sequent-ui, config custom html body include for voting-booth
  become: true
  become_user: ui_user
  replace:
    dest: /home/ui_user/voting-booth/Gruntfile.js
    regexp: 'booth_html_body_include:.*'
    replace: 'booth_html_body_include:"{{ config.sequent_ui.texts.booth_html_body_include | regex_replace("\n", "") }}",'

- name: sequent-ui, config custom html body include for election-portal
  become: true
  become_user: ui_user
  replace:
    dest: /home/ui_user/election-portal/Gruntfile.js
    regexp: 'elections_html_body_include:.*'
    replace: 'elections_html_body_include:"{{ config.sequent_ui.texts.elections_html_body_include | regex_replace("\n", "") }}",'

- name: sequent-ui, check SequentPluginsConfig.js exists
  become: true
  become_user: ui_user
  stat:
    path: /home/ui_user/admin-console/SequentPluginsConfig.js
  register: avpluginsconfig_file

- name: sequent-ui, check SequentConfig version
  become: true
  become_user: ui_user
  shell: cat /home/ui_user/admin-console/SequentConfig.js | grep SEQUENT_CONFIG_VERSION | sed 's/\s*var\s*SEQUENT_CONFIG_VERSION\s*=\s*[\x27|"]\([0-9a-zA-Z\.\-]*\)["|\x27]\s*;\s*/\1/'
  register: config_version
  when: avpluginsconfig_file.stat.exists

- name: sequent-ui, check SequentPluginsConfig version
  become: true
  become_user: ui_user
  shell: cat /home/ui_user/admin-console/SequentPluginsConfig.js | grep SEQUENT_PLUGINS_CONFIG_VERSION | sed 's/\s*var\s*SEQUENT_PLUGINS_CONFIG_VERSION\s*=\s*[\x27|"]\([0-9a-zA-Z\.\-]*\)["|\x27]\s*;\s*/\1/'
  register: plugins_version
  when: avpluginsconfig_file.stat.exists

- name: sequent-ui, remove SequentPluginsConfig.js (a new stub will be automatically generated)
  become: true
  become_user: ui_user
  file: 
    path: "/home/ui_user/{{ item }}/SequentPluginsConfig.js"
    state: absent
  with_items:
    - admin-console
    - voting-booth
    - election-portal
  when: avpluginsconfig_file.stat.exists and config_version.stdout != plugins_version.stdout
