# This file is part of deployment-tool.
# Copyright (C) 2022 Sequent Tech Inc <legal@sequentech.io>

# deployment-tool is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License.

# deployment-tool  is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with deployment-tool.  If not, see <http://www.gnu.org/licenses/>.

---
- name: sequent-ui, Add Apt signing key for google-chrome
  when: config.sequent_ui.enable_self_testing
  become: true
  ansible.builtin.apt_key:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present

- name: sequent-ui, Add google-chrome repository into sources list
  when: config.sequent_ui.enable_self_testing
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: sequent-ui, Install google-chrome
  become: true
  ansible.builtin.apt:
    name: google-chrome-stable
    state: latest
    update_cache: true

- name: sequent-ui, Creating selenium service runner
  become: true
  ansible.builtin.template:
    src: sequent-ui/templates/selenium.sh
    dest: /home/ui_user/selenium.sh
    owner: ui_user
    group: ui_user
    mode: '0744'

- name: sequent-ui, set e2e tests baseUrl setting
  become: true
  become_user: ui_user
  replace:
    dest: /home/ui_user/admin-console/test/e2e.conf.js
    regexp: 'baseUrl:.*'
    replace: 'baseUrl: "https://{{config.sequent_ui.domain}}"'

- name: sequent-ui, Creating selenium service
  become: true
  ansible.builtin.template:
    src: sequent-ui/templates/selenium.conf
    dest: /etc/supervisor/conf.d/selenium.conf
    owner: root
    mode: '0600'

- name: sequent-ui, Creating launch_selftest.sh executable
  become: true
  ansible.builtin.template:
    src: sequent-ui/templates/launch_selftest.sh
    dest: /home/ui_user/launch_selftest.sh
    owner: ui_user
    mode: '0700'

- name: sequent-ui, Creating kill_selftest.sh executable
  become: true
  ansible.builtin.template:
    src: sequent-ui/templates/kill_selftest.sh
    dest: /home/ui_user/kill_selftest.sh
    owner: ui_user
    mode: '0700'

- name: sequent-ui, updating web-driver
  become: true
  become_user: ui_user
  ansible.builtin.shell:
    cmd: ./node_modules/webdriver-manager/bin/webdriver-manager update --ignore_ssl
    chdir: /home/ui_user/admin-console/

- name: sequent-ui, restarting supervisor
  become: true
  ansible.builtin.service:
    name: supervisor
    state: restarted
