# This file is part of agora-dev-box.
# Copyright (C) 2014-2016  Agora Voting SL <agora@agoravoting.com>

# agora-dev-box is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License.

# agora-dev-box  is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with agora-dev-box.  If not, see <http://www.gnu.org/licenses/>.

---
- name: AgoraVerifier, building agora-verifier
  sudo: true
  sudo_user: agoraverifier
  command: /usr/bin/sbt clean proguard:proguard chdir=/home/agoraverifier/agora-verifier

- name: AgoraVerifier, package agora-verifier
  sudo: true
  sudo_user: agoraverifier
  command: sh ./package.sh chdir=/home/agoraverifier/agora-verifier

- name: AgoraVerifier, create dist dir
  sudo: true
  sudo_user: agoraverifier
  file:
    path=/home/agoraverifier/dist/
    state=directory
    mode=0755
    owner=agoraverifier
    group=agoraverifier

- name: AgoraVerifier, link dist binary
  sudo: true
  sudo_user: agoraverifier
  file:
    src=/home/agoraverifier/agora-verifier/agora-verifier
    dest=/home/agoraverifier/dist/agora-verifier
    state=link
    owner=agoraverifier
    group=agoraverifier
