---
- name: AgoraVerifier, building agora-verifier
  sudo: true
  sudo_user: agoraverifier
  command: /usr/bin/sbt clean proguard:proguard chdir=/home/agoraverifier/agora-verifier

- name: AgoraVerifier, package agora-verifier
  sudo: true
  sudo_user: agoraverifier
  command: sh ./package.sh chdir=/home/agoraverifier/agora-verifier

- name: AgoraVerifier, create dist dir
  sudo: true
  sudo_user: agoraverifier
  file:
    path=/home/agoraverifier/dist/
    state=directory
    mode=0755
    owner=agoraverifier
    group=agoraverifier

- name: AgoraVerifier, link dist binary
  sudo: true
  sudo_user: agoraverifier
  file:
    src=/home/agoraverifier/agora-verifier/agora-verifier
    dest=/home/agoraverifier/dist/agora-verifier
    state=link
    owner=agoraverifier
    group=agoraverifier
