#!/bin/bash

# This file is part of deployment-tool.
# Copyright (C) 2014-2016  Sequent Tech Inc <legal@sequentech.io>

# deployment-tool is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License.

# deployment-tool  is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with deployment-tool.  If not, see <http://www.gnu.org/licenses/>.

EOPATH=/home/eorchestra/election-orchestra
SETTINGS=$EOPATH/base_settings.py

[ $(whoami) == "root" ] || (echo "Execute this as root" && exit 1)

if [ "$1" == "true" ]
then
    grep "AUTOACCEPT_REQUESTS = True" $SETTINGS >/dev/null && echo "Autoaccepting requests is already set to TRUE, not doing anything" && exit 0

    sed -i 's/AUTOACCEPT_REQUESTS = False/AUTOACCEPT_REQUESTS = True/g' $EOPATH/base_settings.py
    echo "Autoaccepting requests set to TRUE. Restarting eorchestra.."
    supervisorctl restart eorchestra
    exit 0
elif [ "$1" == "false" ]
then
    grep "AUTOACCEPT_REQUESTS = False" $SETTINGS >/dev/null && echo "Autoaccepting requests is already set to False, not doing anything" && exit 0

    sed -i 's/AUTOACCEPT_REQUESTS = True/AUTOACCEPT_REQUESTS = False/g' $EOPATH/base_settings.py
    echo "Autoaccepting requests set to FALSE. Restarting eorchestra.."
    supervisorctl restart eorchestra
    exit 0
fi

grep "AUTOACCEPT_REQUESTS = False" $SETTINGS >/dev/null && echo "Autoaccepting requests is set to FALSE" || echo "Autoaccepting requests is set to TRUE"
