#!/bin/bash

# This file is part of agora-dev-box.
# Copyright (C) 2014-2016  Agora Voting SL <agora@agoravoting.com>

# agora-dev-box is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License.

# agora-dev-box  is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with agora-dev-box.  If not, see <http://www.gnu.org/licenses/>.

SERVER_PATH=/srv/election-orchestra/server1/public

if [ $1 ]
then
    if [ ! -d $SERVER_PATH/$1 ]
    then
      echo "No election dir starting name $1"
      exit 1
    fi
    if [ -f ${SERVER_PATH}/$1/tally.tar.gz ]
    then
        MYDIR=$(pwd)
        cd /home/eorchestra/election-orchestra && sudo eid=$1 -u eorchestra bash -c  'export FRESTQ_SETTINGS=base_settings.py; /home/eorchestra/venv/bin/python app.py --reset-tally $eid'
        cd $MYDIR
        rm ${SERVER_PATH}/$1/tally.tar.gz ${SERVER_PATH}/$1/tally.tar.gz.sha256
        echo "Removed tally: ${SERVER_PATH}/$1/tally.tar.gz"
        exit 0
    fi
elif [ -d $SERVER_PATH ]
then
    echo "Listing last tallied elections by election id:"
    for i in $(ls -t $SERVER_PATH)
    do
        if [ -f ${SERVER_PATH}/${i}/tally.tar.gz ]
        then
            tdate=$(stat -c%y ${SERVER_PATH}/${i})
            echo " * $i (last modified: $tdate)"
        fi
    done
    exit 0
fi

echo "Not found any tally to remove"
exit 1
