---
- hosts: all

  tasks:
    - include_vars: config.yml
    - include_vars: repos.yml

    - include: java.yml
    - include: packages.yml
    - include: system.yml
    - include: agora-tools/main.yml
    #- include: eorchestra/main.yml
    - include: agora-elections/main.yml
    - include: authapi/main.yml
    - include: agora-gui/main.yml
    - include: sentry/main.yml
    - include: oneserver/main.yml
    - include: agora-verifier/main.yml
