# This file is part of deployment-tool.
# Copyright (C) 2014-2016  Sequent Tech Inc <legal@sequentech.io>

# deployment-tool is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License.

# deployment-tool  is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with deployment-tool.  If not, see <http://www.gnu.org/licenses/>.

---
- name: election-orchestra, Ensure using https in git clone
  become: true
  become_user: eorchestra
  shell: 'git config --global url."https://".insteadOf git://'
  # this is neede because otherwise when installing packages with pip
  # requirements from a git repository, it won't use the http_proxy if
  # configured, see:
  # http://stackoverflow.com/questions/128035/how-do-i-pull-from-a-git-repository-through-an-http-proxy/32744849#32744849
  # http://jgoodall.me/posts/2013/05/29/git-use-https/

- name: election-orchestra, ensure working pip version (21.0)
  become: true
  become_user: eorchestra
  pip:
    virtualenv: /home/eorchestra/venv
    virtualenv_python: python3
    state: present
    name: pip==21.0

- name: election-orchestra, frestq python packages
  become: true
  become_user: eorchestra
  pip:
    virtualenv: /home/eorchestra/venv
    virtualenv_python: python3
    state: present
    requirements: /home/eorchestra/frestq/requirements.txt

- name: election-orchestra, frestq repository in eo requirements.txt setup
  become: true
  become_user: eorchestra
  replace:
    dest: /home/eorchestra/election-orchestra/requirements.txt
    regexp: ".*frestq.*"
    replace: "git+{{ repos.frestq.repo }}.git@{{ repos.frestq.version }}"

- name: election-orchestra, eorchestra python packages
  become: true
  become_user: eorchestra
  pip:
    virtualenv: /home/eorchestra/venv
    virtualenv_python: python3
    state: present
    requirements: /home/eorchestra/election-orchestra/requirements.txt
