# This file is part of agora-dev-box.
# Copyright (C) 2014-2016  Agora Voting SL <agora@agoravoting.com>

# agora-dev-box is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License.

# agora-dev-box  is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with agora-dev-box.  If not, see <http://www.gnu.org/licenses/>.

---
- name: EOrchestra, Ensure using https in git clone
  sudo: true
  sudo_user: eorchestra
  shell: 'git config --global url."https://".insteadOf git://'
  # this is neede because otherwise when installing packages with pip
  # requirements from a git repository, it won't use the http_proxy if
  # configured, see:
  # http://stackoverflow.com/questions/128035/how-do-i-pull-from-a-git-repository-through-an-http-proxy/32744849#32744849
  # http://jgoodall.me/posts/2013/05/29/git-use-https/

- name: EOrchestra, frestq python packages
  sudo: true
  sudo_user: eorchestra
  pip: virtualenv=/home/eorchestra/venv state=present
       requirements=/home/eorchestra/frestq/requirements.txt

- name: EOrchestra, eorchestra python packages
  sudo: true
  sudo_user: eorchestra
  pip: virtualenv=/home/eorchestra/venv state=present
       requirements=/home/eorchestra/election-orchestra/requirements.txt
