---
- name: AgoraGui, npm install
  sudo: true
  sudo_user: agoragui
  when: config.has_https_proxy
  shell: npm --https-proxy=$http_proxy --registry=http://registry.npmjs.org/ --phantomjs_cdnurl=https://cnpmjs.org/downloads install chdir=/home/agoragui/{{ item }}
  with_items:
    - agora-gui-admin
    - agora-gui-elections
    - agora-gui-booth

- name: AgoraGui, npm install
  sudo: true
  sudo_user: agoragui
  when: not config.has_https_proxy
  npm: path=/home/agoragui/{{ item }}
  with_items:
    - agora-gui-admin
    - agora-gui-elections
    - agora-gui-booth

- name: AgoraGui, bower install (proxy)
  sudo: true
  sudo_user: agoragui
  when: config.has_https_proxy
  shell: http_proxy=$http_proxy https_proxy=$http_proxy bower install --config.interactive=false chdir=/home/agoragui/{{ item }}
  with_items:
    - agora-gui-admin
    - agora-gui-elections
    - agora-gui-booth

- name: AgoraGui, bower install
  sudo: true
  sudo_user: agoragui
  when: not config.has_https_proxy
  shell: bower install --config.interactive=false chdir=/home/agoragui/{{ item }}
  with_items:
    - agora-gui-admin
    - agora-gui-elections
    - agora-gui-booth

- name: AgoraGui, Creating build.sh
  sudo: true
  template: src=agora-gui/templates/build.sh dest=/home/agoragui/build.sh owner="agoragui" group="agoragui" mode=0744

- name: AgoraGui, building
  sudo: true
  sudo_user: agoragui
  shell: ./build.sh chdir=/home/agoragui/
