#!/bin/bash

if [ "$(whoami)" != "root" ]
then
    echo "You need to run this as root"
fi

EORCHESTRA_DIR=/home/eorchestra
VENV_DIR=$EORCHESTRA_DIR/venv

source $VENV_DIR/bin/activate
export FRESTQ_SETTINGS=$EORCHESTRA_DIR/election-orchestra/base_settings.py
export PYTHONPATH=/home/eorchestra/frestq

/usr/bin/eotasks.py $* 2>/dev/null