#!/bin/bash

if [ "$(whoami)" != "eorchestra" ]
then
    echo "$0 $*"
    sudo -u eorchestra -i -- sh -c "$0 $*"
    exit 0
fi

EORCHESTRA_DIR=/home/eorchestra
VENV_DIR=$EORCHESTRA_DIR/venv

source $VENV_DIR/bin/activate
export FRESTQ_SETTINGS=$EORCHESTRA_DIR/election-orchestra/base_settings.py
export PYTHONPATH=/home/eorchestra/frestq

echo "/usr/bin/eotasks.py $*"
/usr/bin/eotasks.py $*