#!/bin/bash

# This file is part of agora-dev-box.
# Copyright (C) 2014-2016  Agora Voting SL <agora@agoravoting.com>

# agora-dev-box is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License.

# agora-dev-box  is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with agora-dev-box.  If not, see <http://www.gnu.org/licenses/>.


if [ "$(whoami)" != "eorchestra" ]
then
    echo "$0 $*"
    sudo -u eorchestra -i -- sh -c "$0 $*"
    exit 0
fi

EORCHESTRA_DIR=/home/eorchestra
VENV_DIR=$EORCHESTRA_DIR/venv

source $VENV_DIR/bin/activate
export FRESTQ_SETTINGS=$EORCHESTRA_DIR/election-orchestra/base_settings.py
export PYTHONPATH=/home/eorchestra/frestq

echo "/usr/bin/eotasks.py $*"
/usr/bin/eotasks.py $*