# This file is part of deployment-tool.
# Copyright (C) 2014-2016  Sequent Tech Inc <legal@sequentech.io>

# deployment-tool is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License.

# deployment-tool  is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with deployment-tool.  If not, see <http://www.gnu.org/licenses/>.

---
- name: AgoraVerifier, building election-verifier
  become: true
  become_user: verifier_user
  command:
    cmd: /usr/bin/sbt clean proguard:proguard
    chdir: /home/verifier_user/election-verifier

- name: AgoraVerifier, package election-verifier
  become: true
  become_user: verifier_user
  command:
    cmd: sh ./package.sh
    chdir: /home/verifier_user/election-verifier

- name: AgoraVerifier, create dist dir
  become: true
  become_user: verifier_user
  file:
    path: /home/verifier_user/dist/
    state: directory
    mode: '0755'
    owner: verifier_user
    group: verifier_user

- name: AgoraVerifier, link dist binary
  become: true
  become_user: verifier_user
  file:
    src: /home/verifier_user/election-verifier/election-verifier
    dest: /home/verifier_user/dist/election-verifier
    state: link
    owner: verifier_user
    group: verifier_user
