name: deployment-skel
root: ~/

windows:
  - l: cd /root/
  - s1:
    - ssh BASE-s1
    - sudo -s
  - s1-d: cd /root/BASE-s1/

  - s2:
    - ssh BASE-s2
    - sudo -s
  - s2-d: cd /root/BASE-s2

  - a1:
    - ssh BASE-a1
    - sudo -s
  - a1-l: ssh BASE-a1 sudo eolog
  - a1-d: cd /root/BASE-a1

  - a2:
    - ssh BASE-a2
    - sudo -s
  - a2-l: ssh BASE-a2 sudo eolog
  - a2-d: cd /root/BASE-a2 

  - ae:
    - ssh BASE-s1
    - sudo -s
    - su - ballotbox

  - at:
    - ssh BASE-s1
    - sudo -s
    - su - ballotbox
    - source ~/tenv/bin/activate
    - cd ~/misc-tools

  - adm:
    - ssh BASE-s1
    - sudo -s
    - su - ballotbox
    - source ~/env/bin/activate
    - cd ~/ballot-box/admin

  - nx-l:
    - ssh BASE-s1 sudo tail -F /var/log/nginx/access.log

  - ae-l:
    - ssh BASE-s1 sudo supervisorctl tail -f ballot-box

  - ath-l:
    - ssh BASE-s1 sudo supervisorctl tail -f iam

  - cel-l:
    - ssh BASE-s1 sudo supervisorctl tail -f iam_celery
