---
# this is needed to get the database tables created
- name: AgoraElections, creating tables
  sudo: true
  sudo_user: agoraelections
  shell: expect -c "spawn ../activator-1.2.12-minimal/activator run; sleep 120; close $spawn_id"& sleep 60; wget http://localhost:9000/elections/api/election/1/; [ $? -eq 8 ] && echo "OK"
         chdir=/home/agoraelections/agora-elections

- name: AgoraElections, activator clean & stage
  sudo: true
  sudo_user: agoraelections
  shell: /home/agoraelections/activator-1.2.12-minimal/activator clean; /home/agoraelections/activator-1.2.12-minimal/activator stage
         chdir=/home/agoraelections/agora-elections
