# SPDX-FileCopyrightText: 2014-2023 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only
name: ORT licensing

on:
  push:
    branches:
    - master
    - '[0-9]+.[0-9]+.x'
    tags:
    - '**'
  pull_request:
    branches:
    - master
    - '[0-9]+.[0-9]+.x'

jobs:
  ort:
    uses: sequentech/meta/.github/workflows/ort.yml@main
    with:
      ort-cli-analyze-args: '--package-managers PIP'
