
# SPDX-FileCopyrightText: 2014-2022 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only
name: ORT licensing

on:
  push:
    branches:
    - master
    - '[0-9]+.[0-9]+.x'
    tags:
    - '**'
  pull_request:
    branches:
    - master
    - '[0-9]+.[0-9]+.x'

jobs:
  ort:
    uses: sequentech/ort-config/.github/workflows/ort.yml@main
    with:
      ort-cli-args: > # using the default plus the package managers setting
        --force-overwrite
        --stacktrace
        -P ort.analyzer.enabledPackageManagers=PIP
